### ISSUE TITLE
SEPA IBAN Validierung

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/warehouse#4]
Als yform Validate umsetzen.

**Comment by alexplusde** [comment]
Achtung, Usability-Falle: Manche Leute möchten gerne Leerzeichen einsetzen oder halten ein `0` für ein `O`. Für einfache Validierungen reicht das hier: https://gist.github.com/Q4U/8578496

Als maskierte Eingabe im Frontend wäre das hier nützlich: http://jsfiddle.net/49HVc/1/

Vielleicht ganz spannend dazu dieser Webdienst:
http://www.iban-bic.com/soap0.html?L=

**Comment by alxndr-w** [comment]
https://trustpair.com/validation-iban/ kann alles Mögliche sein.

![image](https://github.com/user-attachments/assets/4eba24f5-74a5-4944-8309-88fc83cf0e72)
